apiVersion: v1
appVersion: "2.32.0.2"
description: A Helm chart for WireMock deployment on Kubernetes
name: wiremock
version: 0.1.4
maintainers:
  - name: "gitkent"
    url: "https://github.com/gitkent"
  - name: "oleg-nenashev"
    url: "https://github.com/oleg-nenashev"
icon: "https://wiremock.org/images/logos/wiremock/logo_square.svg"
home: "https://wiremock.org"
sources:
  - "https://github.com/wiremock/helm-charts"
  - "https://github.com/wiremock/wiremock-docker"
  - "https://github.com/wiremock/wiremock"
keywords:
  - wiremock
  - api
  - openapi
  - api-testing
  - rest-api
  - api-mocking
